### ISSUE TITLE
Support Vaadin 14.4.3+

### ISSUE THREAD

**Issue by kshashov** [vaadin-component-factory/selection-grid-flow#12]
We found that `SelectionTreeGrid` throws an exception at runtime if we use Vaadin 14.4.3+. Looks like the `HierarchyMapper` has been updated in the flow-data library. Are there any plans to support the new Vaadin versions?

```
Caused by: java.lang.NoSuchFieldException: expandedItemIds
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.vaadin.componentfactory.selectiongrid.SelectionTreeGrid.<init>(SelectionTreeGrid.java:71)
```

**Comment by jcgueriaud1** [comment]
Hi,
I can reproduce the error.

The component has a workaround for an issue: https://github.com/vaadin/vaadin-grid/issues/1820 
The issue has been fixed in the framework and probably cause the incompatibility.

I'll check it next week.

**Comment by jcgueriaud1** [comment]
There is a new version in the directory 0.3.0:https://vaadin.com/directory/component/selection-grid
