### ISSUE TITLE
Upgrade for Vaadin 18+

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/selection-grid-flow#16]
The component is not working for Vaadin 18+

**Comment by HerbertsVaadin** [comment]
![image](https://user-images.githubusercontent.com/80950643/112950442-f3dabd80-9142-11eb-80ad-19dd51334767.png)
When clicking on a single row, it seems to select all rows from the bottom up to the selected row.

**Comment by prupp** [comment]
Any plans to add Vaadin 18+ compatibility in the near future?

**Comment by jcgueriaud1** [comment]
I'll try to update the component for Vaadin 23.

**Comment by jcgueriaud1** [comment]
It's updated to Vaadin 23 (version 2.0.0) and will be updated to Vaadin 24 soon.
I'm closing this one since Vaadin 18 is outdated
