### ISSUE TITLE
SelectionTreeGrid: Replace requirement for TreeDataProvider with HierarchicalDataProvider and InMemoryDataProvider.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin-component-factory/selection-grid-flow#20]
Currently the SelectionTreeGrid only allows the usage of a TreeDataProvider. This seems to be unnecessary, since there is no further usage of that specific type or its implementation details (at least not obvious) and leads to issues in cases, where own implementations of a Hierarchical InMemoryDataProvider shall be used. 

Therefore the request is to change the check inside the setDataProvider method to check for HierarchicalDataProvider and InMemoryDataProvider (the later since it seems to be necessary atM to have an InMemoryDataProvider).

**Comment by jcgueriaud1** [comment]
Closed by #26
