### ISSUE TITLE
Remove necessity for InMemoryDataProvider

### ISSUE THREAD

**Issue by stefanuebe** [vaadin-component-factory/selection-grid-flow#24]
Currently the selection tree grid only supports an in memory data provider. Most applications use lazy loading data providers due to huge amounts of data. Therefore it would be helpful, if the STG would also work with such data providers. (Might already work, but the current version requires a TreeDataProvider, which is in memory).

**Comment by jcgueriaud1** [comment]
The shift-click selection range with a lazy data provider could lead to a lot of db requests. It's probably a bad idea to use the component with a huge amount of data, that's why it has been limited. It could work but for sure with cases that will block the application.

**Comment by stefanuebe** [comment]
> The shift-click selection range with a lazy data provider could lead to a lot of db requests. It's probably a bad idea to use the component with a huge amount of data, that's why it has been limited. It could work but for sure with cases that will block the application.

Not sure in which way that should lead to additional db requests beside the ones that already have been done before or that will be done, when scrolling up and down, since the selection should only select expanded items, correct?

**Comment by jcgueriaud1** [comment]
Closed by #26
Released in v0.4.1
