### ISSUE TITLE
SelectionGrid not displaying contents in Vaadin 22.0.2

### ISSUE THREAD

**Issue by finaris-cs** [vaadin-component-factory/selection-grid-flow#33]
Just upgraded from Vaadin 21.0.9 to 22.0.2. I use version 0.5.0 of selection-tree-grid.

As result all my trees (based on SelectionTreeGrid) did not show any content (sometimes a expand/collapse toggle icon is displayed, but not my defined component).
My current workaround is to use TreeGrid instead, this displays the contents, but lacks the nice additional features of SelectionTreeGrid.

A pached version vor Vaadin 22 would be highly appreciated

**Comment by jcgueriaud1** [comment]
The component is not yet compatible with Vaadin 18+.
https://github.com/vaadin-component-factory/selection-grid-flow/issues/16

I'll update the other ticket
