### ISSUE TITLE
Selection using `shift` doesn't work correctly with `setItems()`

### ISSUE THREAD

**Issue by David-Loibl** [vaadin-component-factory/selection-grid-flow#40]
Selecting multiple rows using the `shift` key does not work properly when using `grid.setItems()` to populate the grid (`ctrl` key works as expected).

The typical result is a selection that jumps several rows to the top.

The issue can be reproduced using a Vaadin Starter App with a grid view and replacing the default Grid with SelectionGrid (example attached).

The example uses the following setup:
- Java 17
- Vaadin 24.0.5
- SelectionGrid 3.0.0

Tested in recent versions of Firefox and Chrome.

[gridtest.zip](https://github.com/vaadin-component-factory/selection-grid-flow/files/11601748/gridtest.zip)

**Comment by paodb** [comment]
Fixed by https://github.com/vaadin-component-factory/selection-grid-flow/pull/41
