### ISSUE TITLE
Many warnings on console Vaadin 24.3.3 / SG 3.0.3

### ISSUE THREAD

**Issue by finaris-cs** [vaadin-component-factory/selection-grid-flow#52]
I just updated to the latest versions of Vaadin and selection grid
I see lots of deprecation warnings on the console (currently, the console is really flooded by this):

![image](https://github.com/vaadin-component-factory/selection-grid-flow/assets/19190710/2b928f77-e02d-4101-a2f9-1199dbb43a21)

Primarily, this should be a task for the selection grid, as it should not use the depreacted APIs that are, according to the message, removed with Vaadin 25. Secondary, Vaadin could log these warnings only once per session, which should be sufficient to make aware of the problem.

**Comment by TatuLund** [comment]
Fixed by https://github.com/vaadin-component-factory/selection-grid-flow/commit/6f6521fe03b24a70f80fc967587cabc25a88a772 in version 3.0.4
